name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    uses: Himaan1502/databricks-ci-cd-templates/.github/workflows/validate.yml@main
    with:
      env-file: env/dev.txt
    secrets: inherit
