name: CI/CD for Databricks Bundles

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  # Validate always runs on PRs before merging
  validate:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Checkout Global Templates
        uses: actions/checkout@v4
        with:
          repository: Himaan1502/databricks-ci-cd-templates
          ref: main
          path: ./.github/templates

      - name: Validate Bundle (Dev)
        uses: ./.github/actions/run
        with:
          command: "bundle validate --target dev"
          env-file: env/dev.txt

  # Deploy to Dev on main push
  deploy-dev:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Checkout Global Templates
        uses: actions/checkout@v4
        with:
          repository: Himaan1502/databricks-ci-cd-templates
          ref: main
          path: ./.github/templates

      - name: Deploy to Dev
        uses: ./.github/actions/deploy
        with:
          env-file: env/dev.txt

  # Deploy to UAT after Dev
  deploy-uat:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: deploy-dev
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Checkout Global Templates
        uses: actions/checkout@v4
        with:
          repository: Himaan1502/databricks-ci-cd-templates
          ref: main
          path: ./.github/templates

      - name: Deploy to UAT
        uses: ./.github/actions/deploy
        with:
          env-file: env/uat.txt

  # Deploy to Prod after UAT
  deploy-prod:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: deploy-uat
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Checkout Global Templates
        uses: actions/checkout@v4
        with:
          repository: Himaan1502/databricks-ci-cd-templates
          ref: main
          path: ./.github/templates

      - name: Deploy to Prod
        uses: ./.github/actions/deploy
        with:
          env-file: env/prod.txt
