name: Validate Databricks Bundle

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (dev, uat, prod)"
        required: true
        default: dev

jobs:
  validate:
    uses: Himaan1502/databricks-ci-cd-templates/.github/workflows/validate.yml@main
    with:
      env-file: env/${{ github.event.inputs.environment }}.txt
    secrets: inherit
